# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/154KI0N4R5FPJ9fY9uor6RqOzFB-pmeUP
"""

pip install streamlit yfinance pandas openpyxl

import streamlit as st
import yfinance as yf
import pandas as pd
import io
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

# --- CORE ANALYTICS FUNCTION ---
def calculate_adv_metrics(ticker_symbol: str):
    try:
        ticker = yf.Ticker(ticker_symbol.strip().upper())
        df = ticker.history(period="6mo")

        if df.empty:
            return None

        current_date = df.index[-1].strftime('%Y-%m-%d')
        current_vol = int(df['Volume'].iloc[-1])
        df_hist = df.iloc[:-1] # Exclude live day for historical ADV calculations

        adv_5  = df_hist['Volume'].tail(5).mean()  if len(df_hist) >= 5  else None
        adv_30 = df_hist['Volume'].tail(30).mean() if len(df_hist) >= 30 else None
        adv_60 = df_hist['Volume'].tail(60).mean() if len(df_hist) >= 60 else None
        adv_90 = df_hist['Volume'].tail(90).mean() if len(df_hist) >= 90 else None
        pov_15 = adv_5 * 0.15 if adv_5 is not None else None

        return {
            "Symbol": ticker_symbol.strip().upper(),
            "Current Session Vol": current_vol,
            "5D ADV": round(adv_5) if adv_5 else "N/A",
            "15% of 5D ADV (POV)": round(pov_15) if pov_15 else "N/A",
            "30D ADV": round(adv_30) if adv_30 else "N/A",
            "60D ADV": round(adv_60) if adv_60 else "N/A",
            "90D ADV": round(adv_90) if adv_90 else "N/A"
        }
    except Exception:
        return None

# --- EXCEL FORMATTING FUNCTION ---
def convert_df_to_excel(df_output):
    output = io.BytesIO()
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        df_output.to_excel(writer, sheet_name='Liquidity Analysis', index=False)
        worksheet = writer.sheets['Liquidity Analysis']

        # Classic Navy Theme
        header_fill = PatternFill(start_color="1F4E78", end_color="1F4E78", fill_type="solid")
        header_font = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
        data_font = Font(name="Calibri", size=11, bold=False)

        for col_num in range(1, len(df_output.columns) + 1):
            cell = worksheet.cell(row=1, column=col_num)
            cell.fill = header_fill
            cell.font = header_font
            cell.alignment = Alignment(horizontal="center", vertical="center")

        for row_num in range(2, len(df_output) + 2):
            for col_num in range(1, len(df_output.columns) + 1):
                cell = worksheet.cell(row=row_num, column=col_num)
                cell.font = data_font
                if col_num > 1 and isinstance(cell.value, (int, float)):
                    cell.number_format = '#,##0'

        for col in worksheet.columns:
            max_len = max(len(str(cell.value or '')) for cell in col)
            worksheet.column_dimensions[get_column_letter(col[0].column)].width = max(max_len + 4, 14)

    return output.getvalue()

# --- STREAMLIT USER INTERFACE ---
st.set_page_config(page_title="Liquidity Analytics Dashboard", layout="wide")

st.title("📊 Institutional Liquidity & ADV Model")
st.markdown("Input a ticker symbol or a comma-separated list of tickers to generate trading lookback metrics.")

# User Input Interfaces
input_type = st.radio("Choose Input Method:", ["Single/Multiple Tickers", "Bulk File Upload (.xlsx / .csv)"])

results_list = []

if input_type == "Single/Multiple Tickers":
    user_input = st.text_input("Enter Ticker(s) separated by commas:", value="CPOP, QMMM, LU")
    if st.button("Run Model", type="primary"):
        tickers = [t.strip() for t in user_input.split(",") if t.strip()]
        for ticker in tickers:
            res = calculate_adv_metrics(ticker)
            if res: results_list.append(res)
            else: st.warning(f"Could not retrieve data for ticker: {ticker}")

else:
    uploaded_file = st.file_uploader("Upload spreadsheet containing a 'symbol' column", type=["csv", "xlsx"])
    if uploaded_file and st.button("Process Bulk File", type="primary"):
        if uploaded_file.name.endswith(".csv"):
            df_file = pd.read_csv(uploaded_file)
        else:
            df_file = pd.read_excel(uploaded_file)

        if 'symbol' in df_file.columns:
            tickers = df_file['symbol'].dropna().unique().tolist()
            progress_bar = st.progress(0)
            for idx, ticker in enumerate(tickers):
                res = calculate_adv_metrics(str(ticker))
                if res: results_list.append(res)
                progress_bar.progress((idx + 1) / len(tickers))
        else:
            st.error("The spreadsheet must contain a column named exactly 'symbol' (lowercase).")

# --- DISPLAY & EXPORT RESULTS ---
if results_list:
    df_results = pd.DataFrame(results_list)

    st.subheader("📋 Output Analytics Matrix")
    # Interactive dataframe display with nice rendering
    st.dataframe(df_results.style.format({col: "{:,.0f}" for col in df_results.columns if "ADV" in col or "Vol" in col}))

    # Generate styled Excel file binary in background
    excel_data = convert_df_to_excel(df_results)

    st.download_button(
        label="📥 Download Formatted Excel Report",
        data=excel_data,
        file_name="ADV_Liquidity_Report.xlsx",
        mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    )